### ISSUE TITLE
Cookbook - Pure JavaScript Voice Chat

### ISSUE THREAD

**Issue by Stuyk** [Stuyk/altv-javascript-guide#21]
We need a simple snippet or guide working through Voice Chat integration using the built-in alt:V Voice Chat.

**Acceptance Criteria**

- A guide or snippet that completely shows the voice chat setup.

**Comment by tastydev** [comment]
should this be ready for copy + paste or do u want functional explanation?

**Comment by Stuyk** [comment]
Functional then copy paste
